# Generated by Django 4.0.3 on 2022-03-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='style',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
