# Generated by Django 4.0.3 on 2022-03-29 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_restaurant_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='contact',
            new_name='Instagram',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='menuHighlights',
            new_name='address',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mainInt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='webite',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MenuHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.restaurant')),
            ],
        ),
    ]
